name: Deploy to ECS

on:
  push:
    branches:
      - docker-aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/skill-tree-api:latest \
                       --build-arg SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/skilltree \
                       --build-arg SPRING_DATASOURCE_USERNAME=testuser \
                       --build-arg SPRING_DATASOURCE_PASSWORD=testpassword \
                       --build-arg SPRING_JPA_HIBERNATE_DDL_AUTO=update \
                       --build-arg MYSQL_HOST=db \
                       --build-arg DB_NAME=skilltree \
                       --build-arg MYSQL_DB_USERNAME=testuser \
                       --build-arg MYSQL_DB_PASSWORD=testpassword \
                       --build-arg DB_DDL_POLICY=update \
                       --build-arg API_V1_PREFIX=/api/v1 \
                       --build-arg SPRING_DATASOURCE_VERSION=8.1.0 \
                       .

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skill-tree-api:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster skill-tree-cluster --service skill-tree-cluster-service --force-new-deployment
